### ISSUE TITLE
Move away from conda-forge::cudatoolkit into nvidia::cuda-toolkit

### ISSUE THREAD

**Issue by elgalu** [conda-forge/jaxlib-feedstock#222]
### Comment:

It would be great to move from https://anaconda.org/conda-forge/cudatoolkit (last update 5 months ago) into https://anaconda.org/nvidia/cuda-toolkit (officially supported by NVIDIA and always up-to-date)

```sh
mamba repoquery whoneeds --tree cudatoolkit
```

```
cudatoolkit[11.8.0]
  ├─ ...
  ├─ jaxlib
  ├─ tensorflow-base
  ├─ tensorflow-estimator
  ├─ ...
  └─ magma
```

**Comment by traversaro** [comment]
Just to clarify, since CUDA 12 the conda-forge cuda packages have been moved to individual `cuda-*` packages, see  https://github.com/conda-forge/conda-forge.github.io/issues/1963 . Note in general conda-forge packages can't depend on packages from other channels.
