### ISSUE TITLE
Jaxlib not compatible with the latest Pyarrow

### ISSUE THREAD

**Issue by ilyanoskov** [conda-forge/jaxlib-feedstock#226]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I have discovered that jaxlib prevents installing the latest Pyarrow.

I am not able to create a Conda environment with jax and pyarrow>=14.0. I see that it's because of the pinned libgrpc version (>=1.58.1, <1.59.0a0)

https://github.com/google/jax/issues/19792

### Installed packages

```shell
pyarrow, python3.11, jax
```

### Environment info

```shell
mamba create -n lala python=3.11 jax pyarrow=15 --dry-run
```

**Comment by xhochy** [comment]
This has been solved with the latest build.
