### ISSUE TITLE
Builds broken

### ISSUE THREAD

**Issue by twiecki** [conda-forge/jaxlib-feedstock#249]
Seems like builds have been broken and jaxlib is not getting updated the last few versions.

<img width="457" alt="image" src="https://github.com/conda-forge/jaxlib-feedstock/assets/674200/e78b2d7a-34cd-4fb8-aa5b-01c8528a5f7c">

@jezdez @djsutherland @msarahan

**Comment by twiecki** [comment]
CC
@ericmjl 
@ngam 
@xhochy

**Comment by xhochy** [comment]
Please fix them, not need to open an issue for this.

**Comment by twiecki** [comment]
I thought the issue tracker here is used to highlight and keep track of issues. A PR (which could come from anybody, and doesn't exist yet) can then reference and close the issue. Issues in other projects that are blocked by this can reference this issue (as happened above) to keep track of things. Apologies if I misunderstood what the issue tracker is for here.

**Comment by xhochy** [comment]
We usually only use the failing PRs as a way to communicate about such things. Issues are typically used for raising issues about failures in already built packages, e.g. missing files in a package.

Currently, this is mostly stuck on people rebasing the jaxlib patches on every version. This is sadly a bit time-intensive as:

1. The patches are sometimes on top of XLA and will in the end be patches-in-patches
2. The feedback cycle is really slow as you need to wait hours to see whether the patches actually work.

**Comment by twiecki** [comment]
@xhochy Understood 👍.
