### ISSUE TITLE
CUDA-dependent libraries aren't properly configured to use CUDA from conda

### ISSUE THREAD

**Issue by vyasr** [conda-forge/jaxlib-feedstock#255]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

From inspecting the latest linux-64 CUDA 12 binaries (`jaxlib-0.4.23-cuda120py39h443a19e_202`) of jaxlib, I see RPATHs that look incorrect to me (looking at the _triton.so file):
```
  RPATH                $ORIGIN/../../nvidia/cuda_runtime/lib:$ORIGIN/../nvidia/cuda_runtime/lib:$ORIGIN/../../nvidia/cuda_cupti/lib:$ORIGIN/../nvidia/cuda_cupti/lib:$ORIGIN/../../nvidia/cusolver/lib:$ORIGIN/../nvidia/cusolver/lib:$ORIGIN/../../nvidia/cusparse/lib:$ORIGIN/../nvidia/cusparse/lib:$ORIGIN/../../../..
```

Those paths look suspect to me. For CUDA 12, neither the conda-forge nor the nvidia channel packages should contain an `nvidia` subdirectory of `lib`. From a quick inspection [the recipe looks to be specifying the right dependencies](https://github.com/conda-forge/jaxlib-feedstock/blob/main/recipe/meta.yaml#L57) along with a `cuda-version`, so I don't immediately know where these RPATHs could be coming from. Is something else potentially installing these libraries into the environment? I suspect that this is the reason why jaxlib may not be finding the CUDA libraries inside the conda environment.

### Installed packages

I didn't install anything myself, I was brought here by https://ericmjl.github.io/blog/2024/6/1/how-to-manage-cuda-libraries-within-conda-environments/.

### Environment info

```shell
N/A
```

**Comment by vyasr** [comment]
Got it, thanks. I didn't consider the possibility that these builds were simultaneously designed to support CUDA wheels until after I posted this. I think it's fine for those RPATHs to exist since they simply allow the CUDA wheels to take precedence if they are installed, but it appears that there are RPATHs missing as well and that's resulting in conda CUDA libraries not being found when wheels aren't present (at least that's my read on @ericmjl's [blog post](https://ericmjl.github.io/blog/2024/6/1/how-to-manage-cuda-libraries-within-conda-environments/)). If the CUDA wheels are not installed, then jaxlib should be able to find CUDA libraries installed as conda packages without requiring patching of `LD_LIBRARY_PATH`. An RPATH entry of `$ORIGIN/../../..` would allow for the discovery of conda CUDA libraries installed in `${CONDA_PREFIX}/lib`, but that is not present. I would expect that to be added automatically by the conda compilers ([which are being used in the recipe](https://github.com/conda-forge/jaxlib-feedstock/blob/main/recipe/meta.yaml#L35)), which suggests that somehow the LDFLAGS set by conda-forge's compiler toolchain is not being respected by the jaxlib build.

**Comment by vyasr** [comment]
Hmm actually after a second look I do see a final RPATH entry `$ORIGIN/../../../..` that ought to point into the correct directory within the environment. I'll try and reproduce the issue from the blog post and see what else might be going on here.

**Comment by vyasr** [comment]
OK, sorry for the delay and the noise. There's no issue in the packages, at least for CUDA 12. The issue was in the environment specification used there. Simplifying it down gets me something that works without issues. Here's an environment
```
name: my-env
channels:
    - nvidia # order matters
    - conda-forge
dependencies:
    - cuda-libraries # this is the cuda metapackage
    - cudnn # this is specifically for cudnn
    - cuda-nvcc # ensures that a compatible nvidia C compiler is available!
    # This may be sufficient, but it's probably safer to specify the CUDA built
    # variant explicitly to make the conda solver's job easier.
    #- jaxlib
    - jaxlib=*=*cuda* 
    - cuda-version=12.5
    - jax
```

With this I see:
```
(my-env) vyasr-dt% python -i -c "import jax.numpy as np; a = np.linspace(0, 3, 1000); import jax; print(jax.default_backend()); print(jax.devices()); print(a[:5])"
gpu
[cuda(id=0), cuda(id=1)]
[0.         0.003003   0.00600601 0.00900901 0.01201201]
>>>
```
and to confirm that the right CUDA library is being loaded
```
(main) vyasr-dt% lsof -p $(ps aux | grep "import jax" | grep -v "grep" | awk '{print $2}') | grep cudart
python  139248 vyasr  mem       REG              259,5    729185 15644539 /home/vyasr/miniconda3/envs/my-env/targets/x86_64-linux/lib/libcudart.so.12.5.39
```

In fact, the `nvidia` channel isn't even necessary here. The following file works just as well.
```
name: my-env
channels:
    - conda-forge
dependencies:
    - cuda-libraries # this is the cuda metapackage
    - cudnn # this is specifically for cudnn
    - cuda-nvcc # ensures that a compatible nvidia C compiler is available!
    # This may be sufficient, but it's probably safer to specify the CUDA built
    # variant explicitly to make the conda solver's job easier.
    #- jaxlib
    - jaxlib=*=*cuda* 
    - cuda-version=12.5
    - jax
```

@ericmjl I believe the issues you encountered are likely due to your including the `cudatoolkit` package in your environment. That package should only be necessary for CUDA 11. With CUDA 12, you want to use `cuda-version` plus whichever components you need (or just `cuda` or `cuda-libraries` to get nearly everything, as you noted).

Sorry again for the noise, the feedstock appears to be fine.

**Comment by ericmjl** [comment]
Wow, this is helpful, @vyasr! Thank you for doing a deep dive, and thank you @hawkinsp for responding. The thread is super clarifying for me.

I can confirm that the following `environment.yml` works (at least on my current home GPU tower with a 1080 + system-level installed CUDA), indicating that it isn't necessary to specify `jaxlib=*=*cuda*` to get the cuda-enabled package. That said, I also agree that it's safer to specify the `jaxlib=*=*cuda*` package to help guarantee package resolution to the CUDA-compiled jaxlib.

@vyasr I'm wondering, in the situation where a `conda` environment configuration file may need to support both CUDA11 and CUDA12 + jaxlib (e.g. to ensure portability of the computational environment across cloud instances with varying software stacks -- something I've encountered before), would we need to have two separate `environment.yml` files, one specifying `cudatoolkit` and the other specifying `cuda-version` instead?

**Comment by jakirkham** [comment]
`cuda-version` exists for all CUDA versions ever supported in conda-forge (so back to CUDA 9.2)

**Comment by ericmjl** [comment]
@jakirkham ah yes, thank you for clarifying that! I guess I also should have checked https://anaconda.org/conda-forge/cuda-version/files, which would have given me the answer too. 

For anyone else who arrives at this discussion thread, https://github.com/conda-forge/cuda-version-feedstock/issues/1 is a super helpful reference!

**Comment by vyasr** [comment]
While it is true that the `cuda-version` package exists for all versions of CUDA on conda-forge, I think that comment perhaps misses the point of the original question:

> I'm wondering, in the situation where a conda environment configuration file may need to support both CUDA11 and CUDA12 + jaxlib (e.g. to ensure portability of the computational environment across cloud instances with varying software stacks -- something I've encountered before), would we need to have two separate environment.yml files, one specifying cudatoolkit and the other specifying cuda-version instead?

If you are using conda-forge packages, you _will_ need to maintain separate environment files for CUDA 11 and CUDA 12 because the package structure is different. For CUDA 11 you will need to specify `cudatoolkit`, whereas for CUDA 12 you'll want `cuda` or `cuda-toolkit` (note the hyphen!). In both cases you can use `cuda-version`, but it'll be much more useful in the second case where all the appropriate constraints are set up for package selection. For CUDA 12 you could also be more surgical and only specify a subset of necessary dependencies rather than pulling the entire CTK, but that's more relevant for package maintainers (e.g. setting a minimal set of run dependencies for jaxlib) than for end-user environment files.

If you used packages from the nvidia channel the story is a bit different because the packaging structure change happened sooner, so you might be able to get away with a single environment.yaml file (but CUDA 11 packages on the nvidia channel do contain other packaging issues that were fixed in CUDA 12 that may render the CUDA 11 environment harder to create reliably without extra specifications).
