### ISSUE TITLE
How to test for LLVM errors

### ISSUE THREAD

**Issue by dfm** [conda-forge/jaxlib-feedstock#66]
On the jax issue thread google/jax#5501, I commented that I had found a patch to locally build a functional jaxlib v0.1.71 on my M1 mac.

@xhochy asked (https://github.com/google/jax/issues/5501#issuecomment-918829763):

> Any idea on how to trigger that error only using jaxlib? That would be nice as a test in the conda package of jaxlib to verify that everything is working (jax and jaxlib are built separately on conda-forge).

So I wanted to move that here so as not to add too much conda-forge specific discussion over there.

I think that the problem here (and the problem that the jax folks are facing) is that you can only reproduce this error on an arm64 machine, which I don't think we have access to, right? So while I'm confident that we can probably figure out how to cross-compile reliably for each release, it'll be hard to automatically test those releases until there is a CI service that offers that hardware. That being said, I'm happy to have a go at tracking down a jaxlib-only snippet that reproduces the error; hopefully later today.

**Comment by xhochy** [comment]
> I think that the problem here (and the problem that the jax folks are facing) is that you can only reproduce this error on an arm64 machine, which I don't think we have access to, right? So while I'm confident that we can probably figure out how to cross-compile reliably for each release, it'll be hard to automatically test those releases until there is a CI service that offers that hardware. That being said, I'm happy to have a go at tracking down a jaxlib-only snippet that reproduces the error; hopefully later today.

We have the problem with automated testing on all packages sadly as there is no (public) CI service available that offers M1 CPUs. I would though run the `jaxlib` builds/PRs locally on my personal M1 before merging to check whether things work. Having a check in `jaxlib` itself would ease my workflow a lot.

**Comment by dfm** [comment]
@xhochy: Here's a jaxlib-only snippet that reproduces the error:

```python
import numpy as np
from jaxlib import xla_client as xc
xops = xc.ops

c = xc.XlaBuilder("simple_scalar")
param_shape = xc.Shape.array_shape(np.dtype(np.float32), ())
x = xops.Parameter(c, 0, param_shape)
y = xops.Sin(x)
computation = c.Build()
cpu_backend = xc.get_local_backend("cpu")
compiled_computation = cpu_backend.compile(computation)
```

This comes directly from the [XLA in Python tutorial](https://jax.readthedocs.io/en/latest/notebooks/XLA_in_Python.html) and executes without issue using the patched version of jaxlib that I compiled locally. It raises the LLVM error when using the un-patched version.

I haven't been able to get the patched version to compile properly on GitHub actions yet (it builds but ends up throwing the same error...) so there are definitely still remaining issues!
