### ISSUE TITLE
RFC proposal re cuda builds

### ISSUE THREAD

**Issue by ngam** [conda-forge/jaxlib-feedstock#98]
### Comment:

#97 

we will likely be able to build most on the public CIs; we will also likely have some failures due to connections, memory, timeouts, etc.

Proposals:
1. Adopt a policy to rerun (after merge) for failed builds twice to see if they could rebuild by chance. I assume the failures are gonna be somewhat random (i.e. not deterministic) within the cuda builds, so simply rerunning may fix stuff
2. If rerunning twice (only twice, let's not keep rerunning) one of the maintainers will build locally and ask conda-forge/core to upload.

Let me know what you think.

**Comment by hmaarrfk** [comment]
I think you can always "Edit the readme" to force a rerun of all builds. If the failures are random, doing it 1-2 times should get you through.

**Comment by ngam** [comment]
This is moot, a little change (unvendoring nccl) brought down the build significantly. I expect all builds to pass on the CI
